@startuml 下单流程
start
:开始下单;
:搜索商品;
:选择商品;
:添加商品;
if (判断商品是否为组合商品数据) then(是)
  if(判断当前组合商品是否包含库存前置商品) then(是)
  :打开商品排课页面;
  :选择预排商品;
  else(否)
  endif
else(否)
  :单独商品;
  if(判断当前商品是否为库存前置售卖) then(是)
  :打开商品排课页面;
  :选择预排商品;
  else(否)
  endif;
endif
:将商品添加至已选商品中;
:计算优惠券金额;
:创建订单;
stop
@enduml